# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import CanService_pb2 as CanService__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class CanOperationsStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.StartMessagesStream = channel.unary_stream(
        '/CanOperations/StartMessagesStream',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=CanService__pb2.CanMessage.FromString,
        )
    self.Tx_to_CAN_bus = channel.unary_unary(
        '/CanOperations/Tx_to_CAN_bus',
        request_serializer=CanService__pb2.CanMessage.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )


class CanOperationsServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def StartMessagesStream(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Tx_to_CAN_bus(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CanOperationsServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'StartMessagesStream': grpc.unary_stream_rpc_method_handler(
          servicer.StartMessagesStream,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=CanService__pb2.CanMessage.SerializeToString,
      ),
      'Tx_to_CAN_bus': grpc.unary_unary_rpc_method_handler(
          servicer.Tx_to_CAN_bus,
          request_deserializer=CanService__pb2.CanMessage.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'CanOperations', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
