# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import CanService_pb2 as CanService__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class CanOperationsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartMessagesStream = channel.unary_stream(
                '/CanOperations/StartMessagesStream',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=CanService__pb2.CanMessage.FromString,
                )
        self.SayHello = channel.unary_unary(
                '/CanOperations/SayHello',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=CanService__pb2.testMsg_resp.FromString,
                )
        self.SayHelloAgain = channel.unary_unary(
                '/CanOperations/SayHelloAgain',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=CanService__pb2.testMsg_req.FromString,
                )


class CanOperationsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartMessagesStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SayHello(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SayHelloAgain(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CanOperationsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartMessagesStream': grpc.unary_stream_rpc_method_handler(
                    servicer.StartMessagesStream,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=CanService__pb2.CanMessage.SerializeToString,
            ),
            'SayHello': grpc.unary_unary_rpc_method_handler(
                    servicer.SayHello,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=CanService__pb2.testMsg_resp.SerializeToString,
            ),
            'SayHelloAgain': grpc.unary_unary_rpc_method_handler(
                    servicer.SayHelloAgain,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=CanService__pb2.testMsg_req.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CanOperations', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CanOperations(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartMessagesStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/CanOperations/StartMessagesStream',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            CanService__pb2.CanMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SayHello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CanOperations/SayHello',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            CanService__pb2.testMsg_resp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SayHelloAgain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CanOperations/SayHelloAgain',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            CanService__pb2.testMsg_req.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
