# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CanService.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='CanService.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x10\x43\x61nService.proto\x1a\x1bgoogle/protobuf/empty.proto\"3\n\nCanMessage\x12\n\n\x02Id\x18\x01 \x01(\x05\x12\x0b\n\x03Len\x18\x02 \x01(\x05\x12\x0c\n\x04\x44\x61ta\x18\x03 \x01(\x0c\x32\x87\x01\n\rCanOperations\x12>\n\x13StartMessagesStream\x12\x16.google.protobuf.Empty\x1a\x0b.CanMessage\"\x00\x30\x01\x12\x36\n\rTx_to_CAN_bus\x12\x0b.CanMessage\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_CANMESSAGE = _descriptor.Descriptor(
  name='CanMessage',
  full_name='CanMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Id', full_name='CanMessage.Id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Len', full_name='CanMessage.Len', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Data', full_name='CanMessage.Data', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=100,
)

DESCRIPTOR.message_types_by_name['CanMessage'] = _CANMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CanMessage = _reflection.GeneratedProtocolMessageType('CanMessage', (_message.Message,), dict(
  DESCRIPTOR = _CANMESSAGE,
  __module__ = 'CanService_pb2'
  # @@protoc_insertion_point(class_scope:CanMessage)
  ))
_sym_db.RegisterMessage(CanMessage)



_CANOPERATIONS = _descriptor.ServiceDescriptor(
  name='CanOperations',
  full_name='CanOperations',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=103,
  serialized_end=238,
  methods=[
  _descriptor.MethodDescriptor(
    name='StartMessagesStream',
    full_name='CanOperations.StartMessagesStream',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_CANMESSAGE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Tx_to_CAN_bus',
    full_name='CanOperations.Tx_to_CAN_bus',
    index=1,
    containing_service=None,
    input_type=_CANMESSAGE,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CANOPERATIONS)

DESCRIPTOR.services_by_name['CanOperations'] = _CANOPERATIONS

# @@protoc_insertion_point(module_scope)
