# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(585, 491)
        Dialog.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.button1 = QtWidgets.QPushButton(Dialog)
        self.button1.setGeometry(QtCore.QRect(400, 230, 161, 81))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(10)
        self.button1.setFont(font)
        self.button1.setObjectName("button1")
        self.button1.clicked.connect(self.print_btn1)

        self.checkBox = QtWidgets.QCheckBox(Dialog)
        self.checkBox.setGeometry(QtCore.QRect(420, 20, 101, 41))
        self.checkBox.setChecked(False)
        self.checkBox.setTristate(False)
        self.checkBox.setObjectName("checkBox")
        self.rcv_can_msgs = QtWidgets.QTextEdit(Dialog)
        self.rcv_can_msgs.setGeometry(QtCore.QRect(10, 10, 351, 471))
        self.rcv_can_msgs.setObjectName("rcv_can_msgs")
        self.rcv_can_msgs.append('Can Data')

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.button1.setText(_translate("Dialog", "Press me!"))
        self.checkBox.setText(_translate("Dialog", "CheckBox"))
    def __init__(self):
        self.i=0

    def print_btn1(self):
        print('btn pressed')
        self.rcv_can_msgs.append("btn pressed %d"%self.i)
        self.i += 1

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
